### ISSUE TITLE
Resolving discrepancies between gdi1 and gdi2

### ISSUE THREAD

**Issue by redgcko7** [abacus-gene/hhsd#1]
First of all, thank you for developing this useful program for species delimitation. It has been fun playing around on it with my dataset these past few weeks.

I have a more conceptual question that could potentially lead to an improvement to the program. As the merge and split algorithms are dependent on the thresholds set by the user, I've come across the "awkward solution" (per Leaché et al. 2019) where gdi1 fulfills a threshold to split (or merge), but gdi2 does not, in which case the program decides to split (or merge) the taxa and continue with another iteration. This is due to differing values of theta for each of the populations being compared when calculating the gdi index. I guess my question is, should both gdi1 and gdi2 need to meet the split (or merge) thresholds in order to split (or merge) for the next iteration? I believe this would make more conceptual sense, as the threshold values are meant to differentiate between when we are certain about merging/splitting and when there is ambiguity. When gd1 and gdi2 are on different sides of these thresholds, this suggests a level of ambiguity that is overlooked by the action of the algorithm that, as implemented, only requires one of the two resulting gdi values to meet the threshold.

I'd be interested to hear your thoughts about this.

**Comment by dkornai** [comment]
I added some new features today relating to confidence intervals on the gdi. For example, the output is now:
```
> Proposal results:

node 1  GDI 1  2.5% HPD  97.5% HPD node 2  GDI 2  2.5% HPD  97.5% HPD  merge accepted?
     A   0.04      0.01       0.13      B   0.03      0.01       0.11             True
     C   0.03      0.01       0.11      D   0.02      0.01       0.09             True
```
If you have any ideas for how this can be integrated into the process of resolving conflicts, feel free to share!

**Comment by dkornai** [comment]
The new version of hhsd changes the syntax of `gdi_threshold`. Users must now supply two threshold values. For example, in a split analysis, we can use `gdi_threshold = gt 0.7, gt 0.7`, which only accepts a merge if both gdi values are greater than (gt) 0.7. Alternatively, for a merge analysis, `gdi_threshold = leq 0.2, leq 1.0` will accept any merge where at least one of the populations is not a unique species, with a gdi less than or equal (leq) to 0.2.
