### ISSUE TITLE
Split and merge results too differents. 

### ISSUE THREAD

**Issue by luassoares** [abacus-gene/hhsd#21]
Hello!

I'm Luana, a PhD student studying population genomics and species delimitation in plant species (Petunias) with recent, rapid divergence. I was thrilled to discover your new software—it enabled me to conduct a BPP delimitation analysis, which I've wanted to try for some time. The software ran smoothly, and I’d be happy to share feedback on the checkpoints if you're interested.

I have two main questions, not necessary a issue:

1. Sequence Data:
For my dataset, I’m using low-coverage RADseq (DArT-seq) data. With a reference genome, I generated multilocus sequences through STACKS, processing BAM files in gstacks and filtering in populations with MAF 0.01 and an 80% presence threshold (-R 0.8). From 34,182 loci, I used 8,010 present in all 63 individuals. Does this approach sound appropriate for the BPP analysis?

2. Analysis Results:
I ran both merge and split models without gene flow, however my lineages are quite messy with gene flow/introgression/ILS. Both runs stopped after the first iteration (logs and decisions attached). 
[log_merge.txt](https://github.com/user-attachments/files/17590335/log_merge.txt)
[log_split.txt](https://github.com/user-attachments/files/17590336/log_split.txt)
[decision_merge.csv](https://github.com/user-attachments/files/17590338/decision_merge.csv)
[decision_split.csv](https://github.com/user-attachments/files/17590339/decision_split.csv)
Here are my control files:

```
#MERGE
# output
output_directory = res_sim_merge
# input files
Imapfile = popmap2.txt
seqfile  = full_loci_highland6.phylip 
# guide tree
guide_tree = (PTE,(PI1,(((PSC,PMA),(PGU,(PG2,PS2))),((((PT2,PAW),PAL),PBO),((PIN,PI2),(PRE,PSA))))));
# hierarchical algorithm settings
mode = merge
gdi_threshold = <=0.2, <=1.0

# BPP MCMC settings
threads = 12
burnin =  50000
nsample = 200000
```
 
```
#SPLIT
# output
output_directory = res_sim_split
# input files
Imapfile = popmap2.txt
seqfile  = full_loci_highland6.phylip 
# guide tree
guide_tree = (PTE,(PI1,(((PSC,PMA),(PGU,(PG2,PS2))),((((PT2,PAW),PAL),PBO),((PIN,PI2),(PRE,PSA))))));
# hierarchical algorithm settings
mode = split
gdi_threshold = >=0.7, >=0.5
# BPP MCMC settings
threads = 12
burnin =  50000
nsample = 200000
```

What would be the best way to proceed? Could adjusting the priors help, or might this issue be related to lineage uncertainty due to rapid, recent divergence? Any insights you have would be greatly appreciated!

Thank you for your time and for developing such helpful tools!

**Comment by dkornai** [comment]
Hi, thanks for sharing all the details on your analysis process. I think the data you are using is enough, as the uncertainties on the gdi are quite small. Can I ask what the average loci length is?

May I ask how you inferred the guide tree you are currently using? My recommendation would be to use BPP A11 [joint delimitation and phylogeny inference] to accomplish that first, if this is not what you are already doing. 

I also would recommend that you add in migration events between putative species if you know that gene flow is present. it should change the estimated parameters significantly, and you should have enough data to conduct inference  under this more complicated model

**Comment by luassoares** [comment]
Thank you for the response and guidance!

My loci are fairly short, ranging from 70–150 bp, as they’re RAD loci. For the guide tree, I initially used an ASTRAL tree inferred from the VCF file. I also tried other methods (SNAPP, SVDQuartets, RAxML, NJ), but they showed some incongruence at the tree’s base. I went with ASTRAL as it seemed the most consistent. I’ll look into using BPP A11 as you suggested, thanks for pointing that out.

About migration, inferring gene flow among these populations has been challenging, as they are recently diverged species, with significant ancestral polymorphism. Gene flow/introgression analysis has been inconclusive. Would it make sense to create different migration scenarios to explore how each might impact the species delimitation? Maybe discussing how varying levels or patterns of gene flow might affect the delimitation results.

Thanks again for your time and help!

**Comment by dkornai** [comment]
With respect to alternative migration analyses, I think it would make most sense to add migration events in all suspected places. If no migration is present in reality, the model should infer a rate of 0. You might remove that event from subsequent analyses then.
